- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    #if you are using an Gcloud VM use the developer account to get permission
    #use the gcloud iam service-accounts keys create ~/file.json --iam-account email@developer.gserviceaccount.com 
    service_account_email: email@developer.gserviceaccount.com  
    credentials_file: ~/file.json
    project_id: project-id
    zone: us-west1-a
    machine_type: n1-standard-1
    image_family: centos-7
    image: centos-7

  tasks:

   - name: Launch instances
     gce:
         instance_names: dev
         zone: "{{ zone }}"
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         image_family: "{{ image_family }}"
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"
